import type { WidgetConfig } from "../types";
import { formulaTool, type FormulaTool } from "./tools-formula-kit";

/* 40 formula-driven mini-tools: money, work, home and craft. Each entry is
   pure data — fields become vars a, b, c… in order; `calc` is a JS body. */

type R = (c: WidgetConfig) => { html: string; css: string; js?: string };

export const FORMULAS_A: FormulaTool[] = [
  { id: "tip-table", name: "Tip table", cat: "tools", blurb: "Your bill across five tip rates, one glance.",
    fields: [["Bill total", "48"]], outs: ["10%", "12.5%", "15%", "18%", "20%"],
    calc: "var b=a||0;[10,12.5,15,18,20].forEach(function(r,i){o(i+1,(b*r/100).toFixed(2))})" },
  { id: "capital-gains-calculator", name: "Capital gains", cat: "tools", blurb: "Gain and return between buy and sell.",
    fields: [["Buy price", "1000"], ["Sell price", "1600"]], outs: ["Gain", "Return"],
    calc: "o(1,(b-a).toFixed(2));o(2,a?((b-a)/a*100).toFixed(1)+'%':'—')" },
  { id: "dividend-yield-calculator", name: "Dividend yield", cat: "tools", blurb: "Annual dividend against share price.",
    fields: [["Share price", "80"], ["Annual dividend", "4"]], outs: ["Yield"],
    calc: "o(1,a?((b/a)*100).toFixed(2)+'%':'—')" },
  { id: "expense-ratio-impact", name: "Expense ratio impact", cat: "tools", blurb: "What a fund's fee costs over the years.",
    fields: [["Fund value", "10000"], ["Expense ratio %", "1.5"], ["Years", "20"]], outs: ["Fees paid", "Low-cost alternative"],
    calc: "var r=b/100,y=c;var v=a*Math.pow(1-r,y);o(1,(a-v).toFixed(0));o(2,(a*Math.pow(1.0001,y)).toFixed(0))" },
  { id: "sinking-fund-calculator", name: "Sinking fund", cat: "tools", blurb: "Save per month for a known future bill.",
    fields: [["Goal amount", "6000"], ["Months until due", "18"]], outs: ["Save per month", "Per week"],
    calc: "o(1,b?(a/b).toFixed(2):'—');o(2,b?(a/(b*4.33)).toFixed(2):'—')" },
  { id: "stacked-discount-calculator", name: "Stacked discounts", cat: "tools", blurb: "What two discounts in a row really give.",
    fields: [["Price", "200"], ["First discount %", "20"], ["Second discount %", "15"]], outs: ["Final price", "True discount"],
    calc: "var p=a*(1-b/100)*(1-c/100);o(1,p.toFixed(2));o(2,(100-(p/a*100)).toFixed(1)+'%')" },
  { id: "mortgage-overpayment-calculator", name: "Mortgage overpayment", cat: "tools", blurb: "How much a monthly extra saves overall.",
    fields: [["Balance", "200000"], ["Rate %", "4"], ["Extra per month", "200"]], outs: ["Interest saved", "Paid off early by"],
    calc: "var r=b/1200,m0=a/300;function sim(ex){var bal=a,mi=0,si=0;for(var i=0;i<720;i++){var q=bal*r;si+=q;bal=bal+q-m0-ex;mi++;if(bal<=0)break}return[mi,si]}" +
      "var s1=sim(0),s2=sim(c||0);o(1,(s1[1]-s2[1]).toFixed(0));o(2,(s1[0]-s2[0])+' months earlier')" },
  { id: "billable-hours-target", name: "Billable hours target", cat: "tools", blurb: "Hours to sell for the revenue you want.",
    fields: [["Revenue needed", "60000"], ["Hourly rate", "75"]], outs: ["Billable hours / week"],
    calc: "o(1,b?Math.round(a/52/b)+' h':'—')" },
  { id: "project-bid-calculator", name: "Project bid", cat: "tools", blurb: "Bid price from cost and target margin.",
    fields: [["Cost", "4000"], ["Margin %", "25"]], outs: ["Bid price", "Margin"],
    calc: "o(1,(a/(1-b/100)).toFixed(0));o(2,(a/(1-b/100)-a).toFixed(0))" },
  { id: "day-rate-to-hourly-calculator", name: "Day rate to hourly", cat: "tools", blurb: "The hourly rate hiding in a day rate.",
    fields: [["Day rate", "480"], ["Billable hours per day", "8"]], outs: ["Hourly rate", "Weekly (5 days)"],
    calc: "o(1,b?(a/b).toFixed(2):'—');o(2,(a*5).toFixed(0))" },
  { id: "client-discount-calculator", name: "Client discount", cat: "tools", blurb: "What a percent off really costs you.",
    fields: [["Project price", "6000"], ["Discount %", "10"]], outs: ["Discounted price", "You give up"],
    calc: "var d=a*b/100;o(1,(a-d).toFixed(2));o(2,d.toFixed(2))" },
  { id: "payment-plan-calculator", name: "Payment plan", cat: "tools", blurb: "Split an invoice into equal parts.",
    fields: [["Invoice total", "3000"], ["Number of payments", "3"]], outs: ["Per payment"],
    calc: "o(1,b?(a/b).toFixed(2):'—')" },
  { id: "fire-number-calculator", name: "FIRE number", cat: "tools", blurb: "The pot that funds your spending at 4%.",
    fields: [["Annual spending", "40000"]], outs: ["FIRE number (4% rule)"],
    calc: "o(1,(a*25).toLocaleString())" },
  { id: "mileage-reimbursement-calculator", name: "Mileage reimbursement", cat: "tools", blurb: "Owed amount for business miles.",
    fields: [["Business miles", "340"], ["Rate per mile", "0.38"]], outs: ["Reimbursement"],
    calc: "o(1,(a*b).toFixed(2))" },
  { id: "commission-calculator", name: "Commission", cat: "tools", blurb: "Commission on a sale amount.",
    fields: [["Sale amount", "12000"], ["Rate %", "3"]], outs: ["Commission"],
    calc: "o(1,(a*b/100).toFixed(2))" },
  { id: "raise-percentage-calculator", name: "Raise impact", cat: "tools", blurb: "New salary and the monthly bump.",
    fields: [["Salary", "60000"], ["Raise %", "4"]], outs: ["New salary", "Monthly increase"],
    calc: "var n=a*(1+b/100);o(1,n.toFixed(0));o(2,((n-a)/12).toFixed(0))" },
  { id: "rent-increase-calculator", name: "Rent increase", cat: "tools", blurb: "New rent and the yearly extra.",
    fields: [["Rent", "1450"], ["Increase %", "5"]], outs: ["New rent", "Extra per year"],
    calc: "var n=a*(1+b/100);o(1,n.toFixed(2));o(2,((n-a)*12).toFixed(0))" },
  { id: "late-fee-calculator", name: "Late fee", cat: "tools", blurb: "A flat percent fee on an overdue invoice.",
    fields: [["Invoice amount", "1200"], ["Fee %", "2"]], outs: ["Late fee"],
    calc: "o(1,(a*b/100).toFixed(2))" },
  { id: "cost-per-wear-calculator", name: "Cost per wear", cat: "tools", blurb: "Price divided by honest use.",
    fields: [["Price", "120"], ["Times worn", "40"]], outs: ["Cost per wear"],
    calc: "o(1,b?(a/b).toFixed(2):'—')" },
  { id: "wedding-cost-calculator", name: "Wedding cost", cat: "tools", blurb: "Total from guests and per-head cost.",
    fields: [["Guests", "80"], ["Cost per guest", "95"]], outs: ["Total"],
    calc: "o(1,(a*b).toLocaleString())" },
  { id: "event-budget-per-head-calculator", name: "Event cost per head", cat: "tools", blurb: "Budget divided across the guest list.",
    fields: [["Budget", "5000"], ["Guests", "60"]], outs: ["Per head"],
    calc: "o(1,b?(a/b).toFixed(2):'—')" },
  { id: "moving-box-estimator", name: "Moving box estimator", cat: "tools", blurb: "Boxes for a home, from rooms and people.",
    fields: [["Rooms", "3"], ["People", "2"]], outs: ["Boxes estimate"],
    calc: "o(1,String(a*8+b*4))" },
  { id: "paint-coverage-calculator", name: "Paint coverage", cat: "tools", blurb: "Liters of paint for the coats you want.",
    fields: [["Wall area (m²)", "42"], ["Coats", "2"], ["Coverage (m²/L)", "10"]], outs: ["Paint needed"],
    calc: "o(1,(a*b/c||0).toFixed(1)+' L')" },
  { id: "wallpaper-roll-calculator", name: "Wallpaper rolls", cat: "tools", blurb: "Rolls for a wall, with pattern waste.",
    fields: [["Wall width (m)", "5.2"], ["Wall height (m)", "2.6"], ["Roll length (m)", "10"]], outs: ["Rolls"],
    calc: "o(1,Math.ceil(a*b/c*1.15))" },
  { id: "tile-calculator", name: "Tile calculator", cat: "tools", blurb: "Tiles for an area, plus cutting waste.",
    fields: [["Area (m²)", "8"], ["Tile size (cm²)", "900"], ["Waste %", "10"]], outs: ["Tiles needed"],
    calc: "o(1,Math.ceil(a*10000/b*(1+c/100)))" },
  { id: "btu-calculator", name: "Room BTU", cat: "tools", blurb: "Heating and cooling size for a room.",
    fields: [["Volume (m³)", "48"], ["Insulation quality (1–3)", "2"]], outs: ["BTU needed"],
    calc: "o(1,Math.round(a*135*b).toLocaleString())" },
  { id: "curtain-fabric-calculator", name: "Curtain fabric", cat: "tools", blurb: "Fabric length with fullness and hems.",
    fields: [["Window width (m)", "1.8"], ["Fullness (×)", "2.2"], ["Hems (cm)", "20"]], outs: ["Fabric length (m)"],
    calc: "o(1,(a*b+0.4).toFixed(2)+' m')" },
  { id: "garden-spacing-calculator", name: "Garden spacing", cat: "tools", blurb: "Plants per row from the spacing rule.",
    fields: [["Bed length (m)", "3"], ["Spacing (cm)", "30"]], outs: ["Plants per row"],
    calc: "o(1,b?Math.floor(a*100/b)+1:'—')" },
  { id: "rainwater-collection-calculator", name: "Rainwater collection", cat: "tools", blurb: "Liters collected per year from a roof.",
    fields: [["Roof area (m²)", "80"], ["Rainfall (mm/yr)", "650"]], outs: ["Liters per year"],
    calc: "o(1,Math.round(a*b*0.9).toLocaleString()+' L')" },
  { id: "charcoal-calculator", name: "Charcoal calculator", cat: "tools", blurb: "Charcoal for the guests and hours.",
    fields: [["Guests", "8"], ["Hours", "4"]], outs: ["Charcoal"],
    calc: "o(1,(a*b*0.3).toFixed(1)+' kg')" },
  { id: "pool-volume-calculator", name: "Pool volume", cat: "tools", blurb: "Liters in a rectangular pool.",
    fields: [["Length (m)", "8"], ["Width (m)", "4"], ["Avg depth (m)", "1.4"]], outs: ["Volume"],
    calc: "o(1,Math.round(a*b*c*1000).toLocaleString()+' L')" },
  { id: "soil-volume-calculator", name: "Raised bed soil", cat: "tools", blurb: "Liters of soil to fill a bed.",
    fields: [["Length (m)", "2.4"], ["Width (m)", "1.2"], ["Depth (cm)", "30"]], outs: ["Soil"],
    calc: "o(1,Math.round(a*b*c/100*1000)+' L')" },
  { id: "mulch-calculator", name: "Mulch coverage", cat: "tools", blurb: "Bags of mulch for a bed depth.",
    fields: [["Bed area (m²)", "12"], ["Depth (cm)", "7"]], outs: ["Mulch (60 L bags)"],
    calc: "o(1,Math.ceil(a*b/100*1000/60)+' bags')" },
  { id: "grass-seed-calculator", name: "Grass seed", cat: "tools", blurb: "Seed weight for a lawn area.",
    fields: [["Area (m²)", "50"], ["Rate (g/m²)", "35"]], outs: ["Seed"],
    calc: "o(1,(a*b/1000).toFixed(1)+' kg')" },
  { id: "fence-paint-calculator", name: "Fence paint", cat: "tools", blurb: "Paint for both sides of a fence.",
    fields: [["Fence length (m)", "30"], ["Height (m)", "1.8"], ["Coats", "2"], ["Coverage (m²/L)", "10"]], outs: ["Paint (L)"],
    calc: "o(1,Math.ceil(a*b*2/c)+' L')" },
  { id: "deck-board-calculator", name: "Deck boards", cat: "tools", blurb: "Boards across a deck width.",
    fields: [["Deck width (m)", "4"], ["Board width (mm)", "120"], ["Gap (mm)", "5"]], outs: ["Boards"],
    calc: "o(1,Math.ceil(a*1000/(b+5)))" },
  { id: "concrete-bags-calculator", name: "Concrete bags", cat: "tools", blurb: "Bags for a slab.",
    fields: [["Area (m²)", "6"], ["Depth (cm)", "10"], ["Bag yield (L)", "17"]], outs: ["Bags (25 kg)"],
    calc: "o(1,Math.ceil(a*c/100*1000/b)+' bags')" },
  { id: "gravel-calculator", name: "Gravel coverage", cat: "tools", blurb: "Weight of gravel for a path depth.",
    fields: [["Area (m²)", "15"], ["Depth (cm)", "5"]], outs: ["Gravel"],
    calc: "o(1,Math.round(a*b/100*1600).toLocaleString()+' kg')" },
  { id: "firewood-calculator", name: "Firewood estimate", cat: "tools", blurb: "Stack volume for the heating season.",
    fields: [["Home size (bedrooms)", "2"], ["Winter harshness (×)", "1.2"]], outs: ["Firewood"],
    calc: "o(1,(a*2.5*b).toFixed(1)+' m³')" },
  { id: "dough-hydration-calculator", name: "Dough hydration", cat: "tools", blurb: "Baker's percentage for your dough.",
    fields: [["Flour (g)", "500"], ["Water (g)", "325"]], outs: ["Hydration"],
    calc: "o(1,a?((b/a)*100).toFixed(0)+'%':'—')" },
  { id: "coffee-ratio-calculator", name: "Coffee ratio", cat: "tools", blurb: "Brew strength as a ratio.",
    fields: [["Coffee (g)", "15"], ["Water (g)", "250"]], outs: ["Ratio"],
    calc: "o(1,a?'1 : '+(b/a).toFixed(1):'—')" },
  { id: "candle-wax-calculator", name: "Candle wax", cat: "tools", blurb: "Wax for a batch of vessels.",
    fields: [["Vessels", "6"], ["Wax per vessel (g)", "180"]], outs: ["Wax needed"],
    calc: "o(1,Math.round(a*b)+' g')" },
];

export const renderersA: Record<string, R> = Object.fromEntries(
  FORMULAS_A.map((t) => [t.id, (c: WidgetConfig) => formulaTool(c, t)]),
);
export const metaA = FORMULAS_A.map((t) => ({ id: t.id, name: t.name, cat: t.cat, blurb: t.blurb }));
