import type { WidgetConfig } from "../types";
import { formulaTool, type FormulaTool } from "./tools-formula-kit";

/* 40 more formula tools: fitness, body metrics, unit conversions and daily life. */

type R = (c: WidgetConfig) => { html: string; css: string; js?: string };

export const FORMULAS_B: FormulaTool[] = [
  { id: "vo2-max-calculator", name: "VO2 max estimate", cat: "tools", blurb: "Aerobic fitness from a resting pulse.",
    fields: [["Resting heart rate", "60"]], outs: ["VO2 max (ml/kg/min)"],
    calc: "o(1,(15.3*(220-a)/a).toFixed(1))" },
  { id: "lean-body-mass-calculator", name: "Lean body mass", cat: "tools", blurb: "Weight without fat, from body fat %.",
    fields: [["Weight (kg)", "75"], ["Body fat %", "20"]], outs: ["Lean mass", "Fat mass"],
    calc: "o(1,(a*(1-b/100)).toFixed(1)+' kg');o(2,(a*b/100).toFixed(1)+' kg')" },
  { id: "waist-hip-ratio-calculator", name: "Waist-to-hip ratio", cat: "tools", blurb: "A simple health risk ratio.",
    fields: [["Waist (cm)", "82"], ["Hips (cm)", "98"]], outs: ["Ratio"],
    calc: "var r=b?a/b:0;o(1,r.toFixed(2));o(2,r<0.9?'low risk':r<1?'moderate':'high risk')" },
  { id: "max-heart-rate-calculator", name: "Max heart rate", cat: "tools", blurb: "220 minus age, with training zones.",
    fields: [["Age", "30"]], outs: ["Max HR", "Fat burn zone", "Cardio zone"],
    calc: "var m=220-a;o(1,m+' bpm');o(2,Math.round(m*0.6)+'–'+Math.round(m*0.7));o(3,Math.round(m*0.7)+'–'+Math.round(m*0.85))" },
  { id: "body-surface-area-calculator", name: "Body surface area", cat: "tools", blurb: "Mosteller formula, the clinical standard.",
    fields: [["Weight (kg)", "75"], ["Height (cm)", "178"]], outs: ["BSA (m²)"],
    calc: "o(1,(Math.sqrt(a*b/3600)).toFixed(2))" },
  { id: "calorie-surplus-calculator", name: "Calorie surplus", cat: "tools", blurb: "Daily target for lean gaining.",
    fields: [["Maintenance calories", "2500"], ["Surplus %", "10"]], outs: ["Daily target", "Weekly gain"],
    calc: "var t=a*(1+b/100);o(1,Math.round(t)+' kcal');o(2,(t*7/7700).toFixed(2)+' kg')" },
  { id: "stone-pounds-converter", name: "Stone ⇄ pounds", cat: "tools", blurb: "UK stones to pounds and kilos.",
    fields: [["Stones", "11"]], outs: ["Pounds", "Kilograms"],
    calc: "o(1,(a*14).toFixed(1)+' lb');o(2,(a*6.35029).toFixed(1)+' kg')" },
  { id: "cups-grams-converter", name: "Cups ⇄ grams", cat: "tools", blurb: "Baking volumes to weight by ingredient.",
    fields: [["Cups", "2"], ["Grams per cup", "120"]], outs: ["Grams"],
    calc: "o(1,Math.round(a*b)+' g')" },
  { id: "mm-inches-converter", name: "Millimeters ⇄ inches", cat: "tools", blurb: "Small hardware and 3D printing.",
    fields: [["Millimeters", "25.4"]], outs: ["Inches"],
    calc: "o(1,(a/25.4).toFixed(3)+' in')" },
  { id: "ounces-grams-converter", name: "Ounces ⇄ grams", cat: "tools", blurb: "Kitchen scale conversions.",
    fields: [["Ounces", "8"]], outs: ["Grams"],
    calc: "o(1,(a*28.3495).toFixed(1)+' g')" },
  { id: "kmh-ms-converter", name: "km/h ⇄ m/s", cat: "tools", blurb: "Speed units for physics and wind.",
    fields: [["km per hour", "72"]], outs: ["m per second"],
    calc: "o(1,(a/3.6).toFixed(2)+' m/s')" },
  { id: "nautical-km-converter", name: "Nautical miles ⇄ km", cat: "tools", blurb: "Sea and aviation distances.",
    fields: [["Nautical miles", "12"]], outs: ["Kilometers"],
    calc: "o(1,(a*1.852).toFixed(2)+' km')" },
  { id: "acre-hectare-converter", name: "Acres ⇄ hectares", cat: "tools", blurb: "Land area, both directions.",
    fields: [["Acres", "5"]], outs: ["Hectares", "m²"],
    calc: "o(1,(a*0.404686).toFixed(3)+' ha');o(2,Math.round(a*4046.86).toLocaleString()+' m²')" },
  { id: "px-rem-converter", name: "Pixels ⇄ rem", cat: "tools", blurb: "CSS sizing at any root size.",
    fields: [["Pixels", "24"], ["Root size (px)", "16"]], outs: ["rem"],
    calc: "o(1,b?(a/b).toFixed(3)+' rem':'—')" },
  { id: "data-minutes-calculator", name: "Streaming data time", cat: "tools", blurb: "How long your data lasts while streaming.",
    fields: [["Data (GB)", "5"], ["Bitrate (Mbps)", "5"]], outs: ["Minutes of video"],
    calc: "o(1,b?Math.round(a*8000/b):'—'+' min')" },
  { id: "battery-runtime-calculator", name: "Battery runtime", cat: "tools", blurb: "Hours a device lasts on a charge.",
    fields: [["Capacity (mAh)", "5000"], ["Device draw (mA)", "350"]], outs: ["Runtime"],
    calc: "o(1,b?(a/b).toFixed(1)+' h':'—')" },
  { id: "solar-output-calculator", name: "Solar panel output", cat: "tools", blurb: "Daily energy from panel wattage and sun.",
    fields: [["Panel watts", "400"], ["Sun hours/day", "4.5"], ["Efficiency %", "80"]], outs: ["Wh per day"],
    calc: "o(1,Math.round(a*b*c/100))" },
  { id: "ev-range-calculator", name: "EV range", cat: "tools", blurb: "Kilometers from battery and consumption.",
    fields: [["Battery (kWh)", "60"], ["Useable %", "95"], ["kWh / 100 km", "17"]], outs: ["Range"],
    calc: "o(1,c?Math.round(a*b/100/c*100)+' km':'—')" },
  { id: "tv-distance-calculator", name: "TV viewing distance", cat: "tools", blurb: "Comfortable seat distance for a screen.",
    fields: [["Screen size (in)", "55"]], outs: ["Recommended distance"],
    calc: "o(1,(a*1.2).toFixed(1)+'–'+(a*1.8).toFixed(1)+' m')" },
  { id: "print-size-calculator", name: "Print size", cat: "tools", blurb: "Largest sharp print from pixel width.",
    fields: [["Pixels", "6000"], ["DPI", "300"]], outs: ["Max print width"],
    calc: "o(1,b?(a/b).toFixed(1)+' in':'—')" },
  { id: "grill-time-calculator", name: "Grill time", cat: "tools", blurb: "Minutes per side for a steak thickness.",
    fields: [["Thickness (cm)", "2.5"]], outs: ["Minutes per side", "Total"],
    calc: "var m=Math.round(a*2.2);o(1,m+' min');o(2,m*2+' min')" },
  { id: "pasta-water-ratio", name: "Pasta water ratio", cat: "tools", blurb: "Water and salt for dry pasta.",
    fields: [["Pasta (g)", "250"]], outs: ["Water", "Salt"],
    calc: "o(1,(a*10/1000).toFixed(1)+' L');o(2,(a*10*0.01*1.2).toFixed(1)+' g')" },
  { id: "rice-ratio-calculator", name: "Rice ratio", cat: "tools", blurb: "Water for perfect rice by type.",
    fields: [["Rice (g)", "300"], ["Water ×", "1.5"]], outs: ["Water"],
    calc: "o(1,Math.round(a*b)+' g = '+Math.round(a*b)+' ml')" },
  { id: "cake-tin-converter", name: "Cake tin converter", cat: "tools", blurb: "Scale a recipe for a different tin.",
    fields: [["Recipe tin ⌀ (cm)", "20"], ["Your tin ⌀ (cm)", "24"]], outs: ["Scale factor", "Multiply recipe by"],
    calc: "var f=(b/2)*(b/2)/((a/2)*(a/2));o(1,'×'+f.toFixed(2));o(2,f.toFixed(2))" },
  { id: "oven-conversion-calculator", name: "Oven conversion", cat: "tools", blurb: "Fan oven vs conventional temperatures.",
    fields: [["Conventional °C", "180"]], outs: ["Fan oven", "Gas mark", "°F"],
    calc: "o(1,Math.round(a-20)+' °C');var g=Math.round((a-135)/14.5);o(2,'Mark '+g);o(3,Math.round(a*9/5+32)+' °F')" },
  { id: "shoe-size-converter", name: "Shoe size converter", cat: "tools", blurb: "Foot length to EU, UK and US sizes.",
    fields: [["Foot length (cm)", "26.5"]], outs: ["EU", "UK", "US"],
    calc: "o(1,Math.round(a*1.5+2));o(2,(a/2.54*3-9.5).toFixed(0));o(3,(a/2.54*3-8).toFixed(0))" },
  { id: "ring-size-converter", name: "Ring size converter", cat: "tools", blurb: "Finger circumference to ring sizes.",
    fields: [["Circumference (mm)", "54"]], outs: ["EU / ISO", "US"],
    calc: "o(1,Math.round(a));o(2,(a/2.55).toFixed(1))" },
  { id: "wind-chill-calculator", name: "Wind chill", cat: "tools", blurb: "How cold it actually feels outside.",
    fields: [["Temperature °C", "2"], ["Wind (km/h)", "30"]], outs: ["Feels like"],
    calc: "var v=Math.pow(b,0.16);var w=13.12+0.6215*a-11.37*v+0.3965*a*v;o(1,w.toFixed(1)+' °C')" },
  { id: "heat-index-calculator", name: "Heat index", cat: "tools", blurb: "Apparent temperature in humidity.",
    fields: [["Temperature °C", "32"], ["Humidity %", "65"]], outs: ["Feels like"],
    calc: "var c1=-8.78469475556,c2=1.61139411,c3=2.33854883889,c4=-0.14611605,c5=-0.012308094,c6=-0.0164248277778,c7=0.002211732,c8=0.00072546,c9=-0.000003582;var h=c1+c2*a+c3*b+c4*a*b+c5*a*a+c6*b*b+c7*a*a*b+c8*a*b*b+c9*a*a*b*b;o(1,h.toFixed(1)+' °C')" },
  { id: "dew-point-calculator", name: "Dew point", cat: "tools", blurb: "The temperature air starts condensing.",
    fields: [["Temperature °C", "22"], ["Humidity %", "60"]], outs: ["Dew point"],
    calc: "var g=(17.27*a)/(237.7+a);var d=(17.27*(Math.log(b/100)+g))/(17.27-Math.log(b/100)-g);o(1,d.toFixed(1)+' °C')" },
  { id: "alcohol-units-calculator", name: "Alcohol units", cat: "tools", blurb: "UK units from volume and ABV.",
    fields: [["Volume (ml)", "330"], ["ABV %", "5"]], outs: ["Units"],
    calc: "o(1,(a*b/1000).toFixed(1)+' units')" },
  { id: "brine-salinity-calculator", name: "Brine salinity", cat: "tools", blurb: "Salt percent for your brine.",
    fields: [["Water (g)", "1000"], ["Salt (g)", "60"]], outs: ["Salinity"],
    calc: "o(1,((b/(a+b))*100).toFixed(1)+'%')" },
  { id: "cook-time-adjuster", name: "Cook time adjuster", cat: "tools", blurb: "Recipe time for a different temperature.",
    fields: [["Recipe time (min)", "45"], ["Recipe °C", "180"], ["Your °C", "200"]], outs: ["Adjusted time"],
    calc: "o(1,Math.round(a*(1-(b-c)*0.006))+' min')" },
  { id: "power-converter", name: "Watts ⇄ horsepower", cat: "tools", blurb: "Mechanical power, both ways.",
    fields: [["Kilowatts", "75"]], outs: ["Horsepower"],
    calc: "o(1,(a*1.34102).toFixed(1)+' hp')" },
  { id: "watts-btu-converter", name: "Watts ⇄ BTU/h", cat: "tools", blurb: "Heater and AC ratings.",
    fields: [["Watts", "1500"]], outs: ["BTU/h"],
    calc: "o(1,Math.round(a*3.41214).toLocaleString()+' BTU/h')" },
  { id: "screen-ppi-calculator", name: "Screen PPI", cat: "tools", blurb: "Pixel density of any display.",
    fields: [["Width (px)", "1920"], ["Height (px)", "1080"], ["Diagonal (in)", "24"]], outs: ["PPI"],
    calc: "o(1,(Math.sqrt(a*a+b*b)/c).toFixed(1)+' ppi')" },
  { id: "data-transfer-converter", name: "Data transfer time", cat: "tools", blurb: "How long a download takes.",
    fields: [["Size (GB)", "12"], ["Speed (Mbps)", "100"]], outs: ["Time"],
    calc: "var s=b?a*8000/b:0;o(1,s>=60?(s/60).toFixed(1)+' min':Math.round(s)+' s')" },
  { id: "gear-inches-calculator", name: "Bike gear inches", cat: "tools", blurb: "Classic gearing measure for bikes.",
    fields: [["Chainring teeth", "50"], ["Cassette teeth", "34"], ["Wheel diameter (mm)", "622"]], outs: ["Gear inches"],
    calc: "o(1,b?(a/b*c/25.4).toFixed(1)+'\"':'—')" },
  { id: "sunburn-time-calculator", name: "Sunburn time", cat: "tools", blurb: "Minutes of sun for your SPF and skin.",
    fields: [["Burn time (min)", "15"], ["SPF", "30"]], outs: ["Safe minutes"],
    calc: "o(1,Math.round(a*b)+' min')" },
  { id: "aspect-ratio-calculator", name: "Aspect ratio", cat: "tools", blurb: "Height for a width at any ratio.",
    fields: [["Width (px)", "1920"], ["Ratio (w:h)", "1.7778"]], outs: ["Height"],
    calc: "o(1,Math.round(a/b)+' px')" },
];

export const renderersB: Record<string, R> = Object.fromEntries(
  FORMULAS_B.map((t) => [t.id, (c: WidgetConfig) => formulaTool(c, t)]),
);
export const metaB = FORMULAS_B.map((t) => ({ id: t.id, name: t.name, cat: t.cat, blurb: t.blurb }));
