"use client";

import { useState } from "react";
import { WidgetPreview } from "./WidgetPreview";
import { renderWidget } from "@/lib/widgets/renderers";
import type { WidgetConfig } from "@/lib/widgets/types";

/* MacBook Resources — docks and desktop widgets users install on their
   physical Mac. Each resource previews live and downloads as a working
   Übersicht widget (http://felixhageloh.de/uebersicht): a single .jsx file
   that renders on the desktop with a live clock and true glass styling. */

type Resource = {
  id: string;
  name: string;
  desc: string;
  live: boolean; // live clock via Übersicht command
  config: WidgetConfig;
};

const RESOURCES: Resource[] = [
  {
    id: "dockpro",
    name: "Dynamic Dock · Pro",
    desc: "The full strip: clock & city, now playing, timer, notes, calendar, reactions, activity rings, network speeds, water tracker and your apps — one glass bar.",
    live: true,
    config: { time: "18:16" } as unknown as WidgetConfig,
  },
  {
    id: "dockclassic",
    name: "Classic Dock · Real Icons",
    desc: "A clean macOS dock with the real Finder, Safari, Mail, Messages, Maps, Calendar, Photos, Music, Notes, Terminal and Settings icons. Hover to magnify.",
    live: false,
    config: {} as WidgetConfig,
  },
  {
    id: "dockdev",
    name: "Developer Dock",
    desc: "Branch status, deploy ring, GitHub stars, Linear cycle, Figma edits, network throughput and your dev apps — built for shipping in public.",
    live: false,
    config: {} as WidgetConfig,
  },
  {
    id: "deskclock",
    name: "Desktop Clock & Weather",
    desc: "The classic Übersicht desktop clock with your city, temperature and conditions. Big, thin, out of the way.",
    live: true,
    config: {} as WidgetConfig,
  },
];

function uebersichtFile(res: Resource): string {
  const out = renderWidget(res.id, res.config);
  const position =
    res.id === "deskclock"
      ? ".md-fixture { position: fixed; top: 16%; left: 50%; transform: translateX(-50%); width: max-content; }"
      : ".md-fixture { position: fixed; bottom: 10px; left: 50%; transform: translateX(-50%); width: max-content; max-width: 96vw; }\n" +
        ".md-fixture .md-stage { padding: 4px 6px; border-radius: 22px; }\n" +
        ".md-fixture .md-stage::after { display: none; }";
  const header =
    `// PlanckUi — ${res.name}\n` +
    `// Generated by planckui.vercel.app/macbook-resources\n` +
    `// Install: open Übersicht, then place this file in\n` +
    `//   ~/Library/Application Support/Übersicht/widgets/\n` +
    (res.live
      ? `// The clock is live — it refreshes every 10 seconds.\n`
      : `// \n`) +
    `\n` +
    (res.live
      ? `export const command = \`date "+%H:%M"\`;\nexport const refreshFrequency = 10000;\n\n`
      : "") +
    `export const className = ${JSON.stringify(out.css + "\n" + position)};\n\n` +
    `const html = ${JSON.stringify(out.html)};\n\n` +
    `export const render = ${res.live ? "({ output }) => " : "() => "}` +
    (res.live
      ? `<div dangerouslySetInnerHTML={{ __html: html.replace("__TIME__", (output || "").trim()) }} />;\n`
      : `<div dangerouslySetInnerHTML={{ __html: html }} />;\n`);
  return header;
}

export function MacResources() {
  const [done, setDone] = useState<string | null>(null);

  function download(res: Resource) {
    const file = uebersichtFile(res);
    const blob = new Blob([file], { type: "text/javascript" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `planckui-${res.id}.jsx`;
    a.click();
    URL.revokeObjectURL(a.href);
    setDone(res.id);
    setTimeout(() => setDone(null), 2500);
  }

  return (
    <div className="grid gap-8">
      {RESOURCES.map((res) => (
        <article key={res.id} className="card overflow-hidden">
          <div className="border-b border-line p-3">
            <WidgetPreview type={res.id} config={res.config} className="overflow-hidden rounded-[var(--radius-md)]" />
          </div>
          <div className="flex flex-wrap items-center gap-4 p-5">
            <div className="min-w-0 flex-1">
              <h2 className="font-display text-lg font-semibold">{res.name}</h2>
              <p className="mt-1 text-sm text-ink-3">{res.desc}</p>
            </div>
            <button type="button" className="btn btn-primary btn-sm" onClick={() => download(res)}>
              {done === res.id ? "Downloaded ✓" : "Download for Mac"}
            </button>
          </div>
        </article>
      ))}
    </div>
  );
}
