// PlanckUi — __NAME__
// Generated by planckui.vercel.app/macbook-resources
//
// Install: open Übersicht, then place this file in
//   ~/Library/Application Support/Übersicht/widgets/
//
// What it does on your Mac:
// · the clock is live (system time, refreshed every 3s)
// · apps appear based on what you actually have installed — click to open
// · pin your own set by editing ~/.planckui-dock/apps.txt (one app name per line)
// · Now Playing follows Apple Music or Spotify while something is playing
// · the Vercel tile deploys __PROJECT_PATH__ with one click
// · status lives in ~/.planckui-dock/deploy.status
import { run } from "uebersicht";

const PROJECT_PATH = "__PROJECT_PATH__";
const SHOW_MUSIC = __MUSIC__;
const SHOW_VERCEL = __VERCEL__;
const ICONS = __ICONS_JSON__;

const APP_IDS = {
  "Safari": "safari", "Mail": "mail", "Messages": "messages", "Maps": "maps",
  "Calendar": "calendar", "Photos": "photos", "Music": "music", "Notes": "notes",
  "Terminal": "terminal", "Settings": "settings", "Spotify": "spotify",
  "Discord": "discord", "Telegram": "telegram", "Figma": "figma", "Chrome": "chrome",
  "Notion": "notion", "Arc": "arc", "Obsidian": "obsidian", "Raycast": "raycast",
  "Slack": "slack", "WhatsApp": "whatsapp", "App Store": "appstore",
};

// exposed for inline onclick handlers
window.__plk = {
  open: function (app) { run('open -a "' + app + '"'); },
  playpause: function () {
    run("osascript -e 'tell application \"Music\" to playpause' >/dev/null 2>&1; osascript -e 'tell application \"Spotify\" to playpause' >/dev/null 2>&1 & exit");
  },
  deploy: function () {
    run("mkdir -p ~/.planckui-dock && echo building > ~/.planckui-dock/deploy.status && nohup sh -c 'cd \"" + PROJECT_PATH + "\" && npx vercel deploy --prod > ~/.planckui-dock/deploy.log 2>&1; echo ready >> ~/.planckui-dock/deploy.status' >/dev/null 2>&1 & exit");
  },
};

export const command = `
echo "TIME: $(date +%H:%M)"
if [ "__MUSIC__" = "1" ]; then
  M=$(osascript -e 'tell application "System Events" to if exists (process "Music") then tell application "Music" to if player state is playing then return name of current track & " Â¦ " & artist of current track' 2>/dev/null)
  if [ -n "$M" ]; then
    echo "MUSIC: Apple Music|$M"
  else
    M=$(osascript -e 'tell application "System Events" to if exists (process "Spotify") then tell application "Spotify" to if player state is playing then return name of current track & " Â¦ " & artist of current track' 2>/dev/null)
    if [ -n "$M" ]; then echo "MUSIC: Spotify|$M"; fi
  fi
fi
if [ "__VERCEL__" = "1" ]; then
  D=$(cat ~/.planckui-dock/deploy.status 2>/dev/null)
  echo "DEPLOY: ${D:-idle}"
fi
APPS=""
if [ -f "$HOME/.planckui-dock/apps.txt" ]; then
  APPS=$(sed -E 's/[[:space:]]*$//' "$HOME/.planckui-dock/apps.txt" | tr '\\n' ',' )
else
  for a in "Safari" "Mail" "Messages" "Maps" "Calendar" "Photos" "Music" "Notes" "Terminal" "Settings" "Spotify" "Discord" "Telegram" "Figma" "Chrome" "Notion" "Arc" "Obsidian" "Raycast" "Slack" "WhatsApp"; do
    [ -d "/Applications/$a.app" ] && APPS="$APPS$a,"
  done
fi
echo "APPS: $APPS"
`;

export const refreshFrequency = 3000;

export const className = __CSS__;

const SEP = '<span class="md-sep"></span>';
const ICON = (app) => ICONS[APP_IDS[app]] || "";

function html(s) {
  let h = '<div class="md-fixture"><div class="md-stage"><div class="md-bar">';
  h += '<div class="md-w"><div><div class="md-time">' + (s.time || "") + '</div></div></div>';
  if (s.music && SHOW_MUSIC) {
    const src = s.music.app === "Spotify" ? "spotify" : "applemusic";
    h += SEP + '<div class="md-w"><span class="md-art"></span>' +
      '<div class="md-glass" style="display:flex;align-items:center;gap:9px">' +
      '<div><div class="md-t1">' + s.music.track + '</div><div class="md-t2">' + s.music.artist + '</div></div>' +
      '<span class="md-btn" title="' + s.music.app + '" onclick="__plk.playpause()">' + ICONS["play"] + '</span></div>' +
      '<span style="display:grid;place-items:center">' + (ICONS[src] || "") + '</span></div>';
  } else if (SHOW_MUSIC) {
    h += SEP + '<div class="md-w"><span class="md-art" style="opacity:0.45"></span>' +
      '<div><div class="md-t1" style="opacity:0.6">Nothing playing</div><div class="md-cap">Apple Music · Spotify</div></div></div>';
  }
  if (SHOW_VERCEL) {
    const building = s.deploy === "building";
    h += SEP + '<div class="md-w" title="Deploys ' + PROJECT_PATH + ' with Vercel">' +
      '<span class="md-conn">' + ICONS["vercel"] + '</span>' +
      '<div><div class="md-t1">Vercel</div><div class="md-cap">' + (building ? 'building…' : 'deploy production') + '</div></div>' +
      '<span class="md-btn" style="' + (building ? 'background:oklch(1 0 0/0.06);animation:md-breathe 1s ease-in-out infinite' : 'background:#0a84ff') + '" onclick="__plk.deploy()">' + (building ? ICONS["clock"] : ICONS["up"]) + '</span></div>';
  }
  h += SEP + '<div class="md-apps">';
  s.apps.slice(0, 10).forEach(function (app, i) {
    h += '<span style="--i:' + (i % 10) + '" title="' + app + '" onclick="__plk.open(\'' + app.replace(/'/g, "\\'") + '\')">' + (ICON(app) || "") + '<span class="md-dot"></span></span>';
  });
  h += '</div>' + SEP + '<div class="md-apps"><span title="Vercel" onclick="window.open(\'https://vercel.com/dashboard\')">' + (ICONS["launchpad"] || "") + '</span><span title="Trash" onclick="__plk.open(\'Trash\')">' + (ICONS["trash"] || "") + '</span></div>';
  h += '</div></div></div>';
  return h;
}

export const render = ({ output }) => {
  const s = { time: "", music: null, apps: [], deploy: "idle" };
  (output || "").split("\n").forEach(function (l) {
    if (l.indexOf("TIME: ") === 0) s.time = l.slice(6);
    if (l.indexOf("MUSIC: ") === 0) {
      const p = l.slice(7).split("|");
      s.music = { app: p[0] || "", track: p[1] || "", artist: p[2] || "" };
    }
    if (l.indexOf("APPS: ") === 0) s.apps = l.slice(6).split(",").filter(Boolean);
    if (l.indexOf("DEPLOY: ") === 0) s.deploy = l.slice(8);
  });
  return <div dangerouslySetInnerHTML={{ __html: html(s) }} />;
};
